name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Website
        uses: actions/checkout@v4
        with:
          path: Root-Website
      - name: Checkout Bot
        uses: actions/checkout@v4
        with:
          repository: snowwysillycat/Root-dbot
          path: Root-dbot
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: Root-Website/package-lock.json
      - name: Install dependencies
        run: |
          cd Root-Website
          npm install
      - name: Extract commands
        run: |
          cd Root-Website
          node extract_commands.cjs
      - name: Build Astro
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
